# This file is a template, and might need editing before it works on your project.
before_script:
  - chmod +x ./gradlew

build:
  stage: build
  script: ./gradlew assemble

quality:
  stage: quality
  script: ./gradlew sonarqube -Dsonar.projectKey=%sonar_key% -Dsonar.host.url=%sonar_host% -Dsonar.login=%sonar_login%

test:
  stage: test
  script: ./gradlew test

after_script:
  - echo "End CI"
