# This file is a template, and might need editing before it works on your project.
before_script:
  - chmod +x ./gradlew

build:
  stage: build
  script: ./gradlew assemble

test:
  stage: test
  script: ./gradlew test

after_script:
  - echo "End CI"
